name: ac_flutter_essentials
description: AC Flutter Essentials
version: 0.1.0
repository: https://github.com/anthochamp/flutter-essentials

environment:
  sdk: '>=2.19.5 <4.0.0'

dependencies:
  flutter: 
    sdk: flutter

dev_dependencies:
  ac_lints: ^0.2.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
