name: Validate Flutter project

on: [ push, pull_request ]

jobs:
  lint:
    uses: anthochamp/dev-toolbox/.github/workflows/flutter-lint.yml@c70002bf914d89a5da0cb21cb99fb70e6ebf783e
  test:
    uses: anthochamp/dev-toolbox/.github/workflows/flutter-test.yml@c70002bf914d89a5da0cb21cb99fb70e6ebf783e
