name: Deploy Flutter library

on:
  push:
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]

jobs:
  lint:
    uses: anthochamp/dev-toolbox/.github/workflows/flutter-lint.yml@c70002bf914d89a5da0cb21cb99fb70e6ebf783e
  test:
    uses: anthochamp/dev-toolbox/.github/workflows/flutter-test.yml@c70002bf914d89a5da0cb21cb99fb70e6ebf783e
  publish:
    needs: [lint, test]
    permissions:
      id-token: write
    uses: anthochamp/dev-toolbox/.github/workflows/flutter-lib-publish.yml@c70002bf914d89a5da0cb21cb99fb70e6ebf783e
